import { Component, HostListener, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { ApiService } from '../core/api.service';
import { NotificationService } from '../core/notification.service';
import { Invoice, InvoiceItem, Product } from '../models';

@Component({ selector: 'app-invoices', standalone: true, imports: [FormsModule], template: `
<section class="page-head"><div><h1>Notas fiscais</h1><p>Emita, acompanhe e imprima suas movimentações.</p></div><button class="primary" (click)="startInvoice()">＋ Nova nota fiscal</button></section>
<section class="stats"><article><span class="stat-icon mint">▤</span><div><small>TOTAL DE NOTAS</small><strong>{{ invoices().length }}</strong></div></article><article><span class="stat-icon amber">◷</span><div><small>NOTAS ABERTAS</small><strong>{{ openCount() }}</strong></div></article><article><span class="stat-icon blue">✓</span><div><small>NOTAS FECHADAS</small><strong>{{ invoices().length - openCount() }}</strong></div></article></section>
<section class="panel"><div class="panel-head"><div><h3>Histórico de notas</h3><p>Numeração sequencial e controle de status</p></div><div class="inline"><button class="secondary danger-soft" (click)="simulateFailure()">⚡ Simular falha</button><button class="icon-btn" (click)="load()">↻</button></div></div>
@if (loading()) { <div class="empty">Carregando notas…</div> } @else if (!invoices().length) { <div class="empty"><b>Nenhuma nota emitida</b><span>Crie uma nota e adicione produtos do estoque.</span></div> } @else { <div class="table-wrap"><table><thead><tr><th>NOTA</th><th>EMISSÃO</th><th>ITENS</th><th>STATUS</th><th></th></tr></thead><tbody>@for (n of invoices(); track n.id) {<tr><td><b class="invoice-number">NF {{ pad(n.number) }}</b></td><td>{{ formatDate(n.createdAt) }}</td><td>{{ n.items.length }} produto(s) · {{ itemTotal(n) }} un.</td><td><span class="badge" [class.closed]="n.status === 'CLOSED'">{{ n.status === 'OPEN' ? 'Aberta' : 'Fechada' }}</span></td><td class="right"><button class="print" [disabled]="n.status !== 'OPEN' || printingId() !== null" (click)="print(n)">@if (printingId() === n.id) { <span class="spinner"></span> Processando } @else { ⎙ Imprimir }</button></td></tr>}</tbody></table></div> }</section>
@if (showForm()) { <div class="overlay" (click)="showForm.set(false)"><form class="modal wide" (click)="$event.stopPropagation()" (ngSubmit)="saveInvoice()"><div class="modal-head"><div><span class="eyebrow">EMISSÃO</span><h2>Nova nota fiscal</h2><p>A numeração será gerada automaticamente.</p></div><button type="button" class="close" (click)="showForm.set(false)">×</button></div><div class="item-builder"><label>Produto<select name="product" [(ngModel)]="selectedProductId"><option [ngValue]="0">Selecione um produto</option>@for (p of products(); track p.id) {<option [ngValue]="p.id" [disabled]="p.balance === 0">{{ p.code }} — {{ p.description }} ({{ p.balance }} un.)</option>}</select></label><label class="qty">Quantidade<input name="quantity" [(ngModel)]="quantity" type="number" min="1"></label><button type="button" class="secondary add" (click)="addItem()">Adicionar</button></div>
<div class="items"><h4>Itens da nota</h4>@if (!draftItems().length) {<div class="mini-empty">Nenhum produto adicionado.</div>} @for (item of draftItems(); track item.productId) {<div class="item-row"><div><b>{{ item.productCode }}</b><span>{{ item.productDescription }}</span></div><strong>{{ item.quantity }} un.</strong><button type="button" (click)="removeItem(item.productId)">×</button></div>}</div><div class="actions"><button type="button" class="secondary" (click)="showForm.set(false)">Cancelar</button><button class="primary" [disabled]="saving() || !draftItems().length">{{ saving() ? 'Emitindo…' : 'Emitir nota aberta' }}</button></div></form></div> }
@if (printDocument(); as document) { <section class="print-sheet"><header><div><span>TESTE TÉCNICO</span><h1>NOTA FISCAL</h1></div><strong>NF {{ pad(document.number) }}</strong></header><div class="print-meta"><div><small>EMISSÃO</small><b>{{ formatDate(document.createdAt) }}</b></div><div><small>STATUS</small><b>FECHADA</b></div></div><table><thead><tr><th>CÓDIGO</th><th>PRODUTO</th><th>QUANTIDADE</th></tr></thead><tbody>@for (item of document.items; track item.productId) { <tr><td>{{ item.productCode }}</td><td>{{ item.productDescription }}</td><td>{{ item.quantity }} un.</td></tr> }</tbody><tfoot><tr><td colspan="2">TOTAL DE UNIDADES</td><td>{{ itemTotal(document) }}</td></tr></tfoot></table><footer>Documento processado eletronicamente pelo sistema de controle de estoque e faturamento.</footer></section> }
` })
export class InvoicesComponent implements OnInit {
  private api = inject(ApiService); private notes = inject(NotificationService);
  invoices = signal<Invoice[]>([]); products = signal<Product[]>([]); draftItems = signal<InvoiceItem[]>([]); printDocument = signal<Invoice | null>(null);
  loading = signal(true); saving = signal(false); showForm = signal(false); printingId = signal<number | null>(null);
  selectedProductId = 0; quantity = 1;
  ngOnInit() { this.load(); }
  load() { this.loading.set(true); forkJoin({ invoices: this.api.invoices(), products: this.api.products() }).pipe(finalize(() => this.loading.set(false))).subscribe({ next: ({ invoices, products }) => { this.invoices.set(invoices); this.products.set(products); }, error: () => { this.invoices.set([]); this.products.set([]); } }); }
  startInvoice() { this.draftItems.set([]); this.selectedProductId = 0; this.quantity = 1; this.showForm.set(true); }
  addItem() { const quantity = Number(this.quantity); const p = this.products().find(x => x.id === Number(this.selectedProductId)); if (!p || !Number.isInteger(quantity) || quantity < 1) { this.notes.show('Selecione um produto e uma quantidade inteira válida.', 'error'); return; } if (quantity > p.balance) { this.notes.show(`Saldo máximo disponível: ${p.balance}.`, 'error'); return; } const current = this.draftItems().filter(x => x.productId !== p.id); this.draftItems.set([...current, { productId: p.id, productCode: p.code, productDescription: p.description, quantity }]); this.selectedProductId = 0; this.quantity = 1; }
  removeItem(id: number) { this.draftItems.update(items => items.filter(x => x.productId !== id)); }
  saveInvoice() { if (!this.draftItems().length) return; this.saving.set(true); this.api.createInvoice(this.draftItems()).pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.notes.show('Nota fiscal criada com status Aberta.', 'success'); this.showForm.set(false); this.load(); }, error: () => undefined }); }
  print(n: Invoice) { if (n.status !== 'OPEN' || this.printingId() !== null) return; this.printingId.set(n.id); this.api.printInvoice(n.id).pipe(finalize(() => this.printingId.set(null))).subscribe({ next: closedInvoice => { this.printDocument.set(closedInvoice); this.notes.show(`NF ${this.pad(n.number)} processada. Estoque atualizado.`, 'success'); this.load(); setTimeout(() => window.print(), 50); }, error: () => this.load() }); }
  @HostListener('window:afterprint') clearPrintDocument() { this.printDocument.set(null); }
  simulateFailure() { this.api.failNextDebit().subscribe({ next: ({ message }) => this.notes.show(message, 'info'), error: () => undefined }); }
  openCount() { return this.invoices().filter(n => n.status === 'OPEN').length; }
  itemTotal(n: Invoice) { return n.items.reduce((sum, x) => sum + x.quantity, 0); }
  pad(value: number) { return String(value).padStart(6, '0'); }
  formatDate(value: string) { return new Date(value.replace(' ', 'T') + 'Z').toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' }); }
}
